site_name: 上海交通大学科幻奇幻协会
site_url: https://gpabooks.github.io/
theme:
  name: material
  language: zh
  logo: assets/images/logo-white.svg
  favicon: assets/images/logo.svg
  custom_dir: docs/overrides
  features:
    - header.autohide #自动隐藏导航栏
    - navigation.tabs
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - search.share
    - content.footnote.tooltips
  
  palette:  # 配色方案：默认模式
    # 浅色模式
    - scheme: default
      accent: deep purple
      toggle:
        icon: fontawesome/brands/sith
        name: Dark side
 
    # 深色模式
    - scheme: slate
      accent: deep purple
      toggle:
        icon: fontawesome/brands/jedi
        name: Light side

  plugins:
    - search:
        lang:
          - zh
          - en
    - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - custom-skip-class-name
        auto_caption: false
        caption_position: bottom
        background: white
        shadow: true
        manual: false
  
markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/weixin
      link: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzI3NDAzNTk2Mg==&scene=124#wechat_redirect
    - icon: fontawesome/brands/weibo
      link: https://www.weibo.com/2395482420
    - icon: douban
      link: https://www.douban.com/people/54420442
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/387123490
    - icon: fontawesome/brands/github
      link: https://github.com/gpabooks/gpabooks.github.io

#css
#extra_css: 
  #- assets/stylesheets/fonts.css #字体设置英文Times New Roman，中文宋体

  
nav:
  - 主页:
    - index.md
  - GPA:
    - gpa/index.md
    - 卷首语: gpa/我来，我看，我叙事.md

    - 我与科幻·我与交大幻协:
      - 家住吴门，就作长安旅——记星云奖太原行: gpa/sff/家住吴门，就作长安旅——记星云奖太原行.md
      - 中国科幻大会观察日记: gpa/sff/中国科幻大会观察日记.md
      - 交集不为空——我与科幻的记忆: gpa/sff/交集不为空——我与科幻的记忆.md
      - 人人都爱写科幻: gpa/sff/人人都爱写科幻.md
      - 美好人生的关键所在: gpa/sff/美好人生的关键所在.md

    - 超短篇小说:
      - 半脑天才: gpa/chaoduanpian/半脑天才.md
      - 壶中记: gpa/chaoduanpian/壶中记.md
      - See you again: gpa/chaoduanpian/See you again.md

    - 短中篇小说:
      - 我们在交大造火箭: gpa/duanzhongpian/我们在交大造火箭.md
      - 初中小登怒写投稿拯救GPA大社刊: gpa/duanzhongpian/初中小登怒写投稿拯救GPA大社刊.md
      - 有限剑制: gpa/duanzhongpian/有限剑制.md

    - 趣文:
      - 新世界设定随笔: gpa/qw/新世界设定随笔.md
      - Tales of KOTOR——旧共和国武士彩蛋小集锦: gpa/qw/Tales of KOTOR——旧共和国武士彩蛋小集锦.md

    - 评论·随笔:
      - 奇幻之路——《巨龙的颂歌》书评: gpa/comment/奇幻之路——《巨龙的颂歌》书评.md
      - 有感迈克尔·克莱顿: gpa/comment/有感迈克尔·克莱顿.md
      - 感受南茜·特蕾丝: gpa/comment/感受南茜·特蕾丝.md
      - 我所憧憬的近未来——弗诺·文奇“彩虹尽头”的世界: gpa/comment/我所憧憬的近未来——弗诺·文奇“彩虹尽头”的世界.md
      - 评论两则: gpa/comment/评论两则.md
      - 一代人的成人礼——人类学视阈下的《超新星纪元》: gpa/comment/一代人的成人礼——人类学视阈下的《超新星纪元》.md

    - 翻译作品:
      - 天降谎言之水 (The Water That Falls on You from Nowhere): gpa/trans/天降谎言之水 (The Water That Falls on You from Nowhere).md

    - 时光掠影:
      - 交大幻协活动掠影2002-2024: gpa/timeflies/交大幻协活动掠影2002-2024.md
      - 寄语: gpa/timeflies/寄语.md

    - 摄影专栏: gpa/摄影专栏.md
    - 科幻奇幻笑话: gpa/科幻奇幻笑话.md

  - SCI:
    - sci/index.md
    - 卷首语: sci/卷首语.md
    - 我与交大幻协:
      - 我们幻协，一段勾史: sci/我与交大幻协/我们幻协，一段勾史.md
    - 小说:
      - 重逢: sci/小说/重逢.md
      - 安得广厦: sci/小说/安得广厦.md
      - 一个陌生机器人的来信: sci/小说/一个陌生机器人的来信.md
    - 漫画: sci/漫画.md
    - 科幻奇幻笑话: sci/科幻奇幻笑话.md
    - 评论·趣文:
      - sci/评论·趣文/Outer Wilds Adventure.md
      - sci/评论·趣文/“朋友”，这对吗？.md
      - sci/评论·趣文/给中国科幻一粒西地那非.md
    - 翻译作品:
      - sci/翻译作品/昆雅语课程绪论（Quenya Course Intro）.md
    - 活动掠影:
      - sci/活动掠影/交大幻协2024-2025年活动掠影.md